// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krgurabeqgokjkkfsygf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyZ3VyYWJlcWdva2pra2ZzeWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MjkwNzcsImV4cCI6MjA1NTIwNTA3N30._OlyRNkek9xjUC88zKhUuR4T3mlYI0rwo6lLH4MyK20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);